## Notebook de la sesión 5
**Nombre:** Pablo Santizo\
**Carné:** 24000134\
**Curso** Ciencia de Datos en Python\
**Maestría:** Data Science\
**Universidad:** Galileo, Instituto en Investigación de Operaciones

# 1.Reshape

In [1]:
import numpy as np

In [2]:
x=np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
x.shape

(10,)

In [16]:
np.reshape(x,(2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.reshape(x,(5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
np.reshape(x,(10,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [19]:
np.reshape(x,(-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [20]:
x.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# 2.Performance

In [33]:
from time import time

In [34]:
x= np.linspace(1,1000000,20000000)
b0=5
b1=2

In [35]:
y = np.empty_like(x)
inicio=time()
for index, value in enumerate(x):
    y[index] = b0 +b1*value
fin=time()

print("El tiempo total es:", fin - inicio)

El tiempo total es: 11.5036780834198


In [61]:
x= np.linspace(1,1000000,20000000)

In [62]:
vect1= np.ones_like(x).reshape((-1,1))
x=x.reshape((-1,1))
A= np.hstack([vect1,x])
betas=np.array([[b0],[b1]])

inicio=time()
y1=np.matmul(A,betas)
fin=time()

print("El tiempo total es:", fin - inicio)

El tiempo total es: 0.07452011108398438


In [54]:
betas

array([[5],
       [2]])

In [51]:
A

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

# 3. Pandas-(Panel Data)

In [65]:
import numpy as np
import pandas as pd

In [68]:
data= np.random.rand(10)
data

array([0.5358803 , 0.83056244, 0.72429598, 0.55579015, 0.13724698,
       0.46801253, 0.94385341, 0.75639273, 0.72208789, 0.10493494])

In [118]:
pd.Series(data,index=np.arange(10,110,10))

10     0.535880
20     0.830562
30     0.724296
40     0.555790
50     0.137247
60     0.468013
70     0.943853
80     0.756393
90     0.722088
100    0.104935
dtype: float64

In [119]:
diccionario = {"A":30,"B":30,"C":"Hola a todos","D": np.exp(5)}
diccionario

{'A': 30, 'B': 30, 'C': 'Hola a todos', 'D': 148.4131591025766}

In [120]:
pd.Series(diccionario)

A              30
B              30
C    Hola a todos
D      148.413159
dtype: object

In [141]:
d = { 'columnaA': [10, 20, 30, 40],
         'columnaB': pd.Series(['abc', 10.5, 34, 'xy']),
         'columnaC': pd.Series([10.45, 89.34, 90.76, 24.89])
     }

df1=pd.DataFrame(d)
df1

columnaA columnaB  columnaC
0        10      abc     10.45
1        20     10.5     89.34
2        30       34     90.76
3        40       xy     24.89

In [131]:
type(df1["columnaB"]) #seleccionar una columna

pandas.core.series.Series

In [132]:
df1.columnaA #seleccionar una columna

0    10
1    20
2    30
3    40
Name: columnaA, dtype: int64

In [133]:
df1["columnaA"]

0    10
1    20
2    30
3    40
Name: columnaA, dtype: int64

In [134]:
df1[["columnaA","columnaC"]]

columnaA  columnaC
0        10     10.45
1        20     89.34
2        30     90.76
3        40     24.89

In [135]:
#Extracción de información en base al nombre de fila (index) y columna
df1.loc[[0,1,3],["columnaA","columnaC"]] #loc hace referencia a location, no es una función

columnaA  columnaC
0        10     10.45
1        20     89.34
3        40     24.89

In [136]:
#Extracci[on de informaci[on enbase al n[umero de fila y columna
df1.iloc[[0,1,3],[2,0]] # se puede indexar por un indice númerico

columnaC  columnaA
0     10.45        10
1     89.34        20
3     24.89        40

In [138]:
#columna nueva
df1["nueva"] = df1[ "columnaA"] + df1["columnaC"]

In [140]:
df1

columnaA columnaB  columnaC   nueva
0        10      abc     10.45   20.45
1        20     10.5     89.34  109.34
2        30       34     90.76  120.76
3        40       xy     24.89   64.89

In [143]:
#eliminar elementos
#axis = 0 -> operamos sobre las filas
#axis = 1 -> operamos sobre las columnas
#inplace =True -> modifica la variable original con la operación aplicada.
df1.drop(3,axis=0,inplace=True) #inplace modifica la variable original

In [144]:
df1

columnaA columnaB  columnaC
0        10      abc     10.45
1        20     10.5     89.34
2        30       34     90.76

In [145]:
# 3.1 Filtros

In [150]:
df2 = pd.DataFrame({
    'A': np.random.randint(1, 20, size=10),
    'B': np.random.randint(1, 20, size=10)
})

df2

A   B
0   1  13
1   7  12
2  15  14
3   9   9
4  12   7
5   8  17
6   5   2
7  11   5
8  10  19
9   7  19

In [151]:
df2["A"]>10

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7     True
8    False
9    False
Name: A, dtype: bool

In [156]:
df2[(df2["A"]>7) & (df2["A"]<10)]

A   B
3  9   9
5  8  17

In [160]:
df1.loc[:,["columnaB"]]

columnaB
0      abc
1     10.5
2       34

## 3.1 - Operaciones de Agregación

In [182]:
df = pd.DataFrame({'col1': [10,20,30,40,50,60], 
                   'col2':[1,2,3,4,5,6], 
                   'col3':['A', 'B', 'C', 'D', 'A', 'F']})

df

col1  col2 col3
0    10     1    A
1    20     2    B
2    30     3    C
3    40     4    D
4    50     5    A
5    60     6    F

In [183]:
df["col1"].sum()

210

In [184]:
#axis=0 operación sobre columnas
#axis=1 operación sobre fila(indices)
df.sum(axis=0)

col1       210
col2        21
col3    ABCDAF
dtype: object

In [185]:
df[["col1","col2"]].sum(axis=1)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [186]:
#cuenta cantidad de filas en la columna
df["col2"].count()

6

In [187]:
#cuenta cantidad de ocurrencias de cada elemento
df["col3"].value_counts()

col3
A    2
B    1
C    1
D    1
F    1
Name: count, dtype: int64

In [190]:
#devuelve arreglo de numpy con valores de una columna
df["col2"].values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [191]:
#devuelve arreglo con nombres de columnas
df.columns.values

array(['col1', 'col2', 'col3'], dtype=object)

# Analytics con Pandas

In [195]:
dataset= pd.read_csv("hotel_bookings.csv")
dataset.head(5)

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

In [196]:
dataset.shape

(119390, 32)

In [200]:
dataset.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             

In [201]:
dataset["is_canceled"].value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [202]:
dataset["lead_time"].value_counts()

lead_time
0      6345
1      3460
2      2069
3      1816
4      1715
       ... 
400       1
370       1
532       1
371       1
463       1
Name: count, Length: 479, dtype: int64